package com.computec.sitevisit.model.uiview;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Oct 12 14:02:29 EEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CliprojVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public CliprojVOImpl() {
    }


    /**
     * Returns the bind variable value for currentClino.
     * @return bind variable value for currentClino
     */
    public String getcurrentClino() {
        return (String) getNamedWhereClauseParam("currentClino");
    }

    /**
     * Sets <code>value</code> for bind variable currentClino.
     * @param value value to bind as currentClino
     */
    public void setcurrentClino(String value) {
        setNamedWhereClauseParam("currentClino", value);
    }
}

