package com.computec.sitevisit.model.uiview;

import com.computec.sitevisit.model.entity.SitevstEOImpl;
import com.computec.sitevisit.model.common.ADFUtil;

import java.math.BigDecimal;
import java.sql.Timestamp;

import oracle.adf.model.BindingContext;
import oracle.adf.model.binding.DCIteratorBinding;
import oracle.binding.BindingContainer;
import oracle.binding.OperationBinding;
import oracle.jbo.Key;
import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 06 12:27:58 EEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SitevstVORowImpl extends ViewRowImpl {
    public static final int ENTITY_SITEVSTEO = 0;
    public static final int ENTITY_EMPLOYEEEO = 1;
    public static final int ENTITY_CLIENTEO = 2;
    public static final int ENTITY_USERSEO = 3;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        SitevstId,
        Soccode,
        Bracode,
        Batchno,
        DateVst,
        Empno,
        Clino,
        TimeFrm,
        TimeTo,
        CliRsp,
        VstPeriod,
        EmpRate,
        Empno1,
        EmpName,
        CliName,
        Clino1,
        Sheetno,
        HrFrm,
        MinFrm,
        HrTo,
        MinTo,
        TtlHrs,
        TtlRatedHrs,
        Remarks,
        UName,
        Work,
        ClientVO1,
        EmployeeVO1;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SITEVSTID = AttributesEnum.SitevstId.index();
    public static final int SOCCODE = AttributesEnum.Soccode.index();
    public static final int BRACODE = AttributesEnum.Bracode.index();
    public static final int BATCHNO = AttributesEnum.Batchno.index();
    public static final int DATEVST = AttributesEnum.DateVst.index();
    public static final int EMPNO = AttributesEnum.Empno.index();
    public static final int CLINO = AttributesEnum.Clino.index();
    public static final int TIMEFRM = AttributesEnum.TimeFrm.index();
    public static final int TIMETO = AttributesEnum.TimeTo.index();
    public static final int CLIRSP = AttributesEnum.CliRsp.index();
    public static final int VSTPERIOD = AttributesEnum.VstPeriod.index();
    public static final int EMPRATE = AttributesEnum.EmpRate.index();
    public static final int EMPNO1 = AttributesEnum.Empno1.index();
    public static final int EMPNAME = AttributesEnum.EmpName.index();
    public static final int CLINAME = AttributesEnum.CliName.index();
    public static final int CLINO1 = AttributesEnum.Clino1.index();
    public static final int SHEETNO = AttributesEnum.Sheetno.index();
    public static final int HRFRM = AttributesEnum.HrFrm.index();
    public static final int MINFRM = AttributesEnum.MinFrm.index();
    public static final int HRTO = AttributesEnum.HrTo.index();
    public static final int MINTO = AttributesEnum.MinTo.index();
    public static final int TTLHRS = AttributesEnum.TtlHrs.index();
    public static final int TTLRATEDHRS = AttributesEnum.TtlRatedHrs.index();
    public static final int REMARKS = AttributesEnum.Remarks.index();
    public static final int UNAME = AttributesEnum.UName.index();
    public static final int WORK = AttributesEnum.Work.index();
    public static final int CLIENTVO1 = AttributesEnum.ClientVO1.index();
    public static final int EMPLOYEEVO1 = AttributesEnum.EmployeeVO1.index();

    /**
     * This is the default constructor (do not remove).
     */
    public SitevstVORowImpl() {
    }

    /**
     * Gets SitevstEO entity object.
     * @return the SitevstEO
     */
    public SitevstEOImpl getSitevstEO() {
        return (SitevstEOImpl) getEntity(ENTITY_SITEVSTEO);
    }

    /**
     * Gets EmployeeEO entity object.
     * @return the EmployeeEO
     */
    public EntityImpl getEmployeeEO() {
        return (EntityImpl) getEntity(ENTITY_EMPLOYEEEO);
    }

    /**
     * Gets ClientEO entity object.
     * @return the ClientEO
     */
    public EntityImpl getClientEO() {
        return (EntityImpl) getEntity(ENTITY_CLIENTEO);
    }

    /**
     * Gets UsersEO entity object.
     * @return the UsersEO
     */
    public EntityImpl getUsersEO() {
        return (EntityImpl) getEntity(ENTITY_USERSEO);
    }

    /**
     * Gets the attribute value for SITEVST_ID using the alias name SitevstId.
     * @return the SITEVST_ID
     */
    public DBSequence getSitevstId() {
        return (DBSequence) getAttributeInternal(SITEVSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for SITEVST_ID using the alias name SitevstId.
     * @param value value to set the SITEVST_ID
     */
    public void setSitevstId(DBSequence value) {
        setAttributeInternal(SITEVSTID, value);
    }

    /**
     * Gets the attribute value for SOCCODE using the alias name Soccode.
     * @return the SOCCODE
     */
    public String getSoccode() {
        return (String) getAttributeInternal(SOCCODE);
    }

    /**
     * Sets <code>value</code> as attribute value for SOCCODE using the alias name Soccode.
     * @param value value to set the SOCCODE
     */
    public void setSoccode(String value) {
        setAttributeInternal(SOCCODE, value);
    }

    /**
     * Gets the attribute value for BRACODE using the alias name Bracode.
     * @return the BRACODE
     */
    public String getBracode() {
        return (String) getAttributeInternal(BRACODE);
    }

    /**
     * Sets <code>value</code> as attribute value for BRACODE using the alias name Bracode.
     * @param value value to set the BRACODE
     */
    public void setBracode(String value) {
        setAttributeInternal(BRACODE, value);
    }

    /**
     * Gets the attribute value for BATCHNO using the alias name Batchno.
     * @return the BATCHNO
     */
    public String getBatchno() {
        return (String) getAttributeInternal(BATCHNO);
    }

    /**
     * Sets <code>value</code> as attribute value for BATCHNO using the alias name Batchno.
     * @param value value to set the BATCHNO
     */
    public void setBatchno(String value) {
        setAttributeInternal(BATCHNO, value);
    }

    /**
     * Gets the attribute value for DATE_VST using the alias name DateVst.
     * @return the DATE_VST
     */
    public Timestamp getDateVst() {
        return (Timestamp) getAttributeInternal(DATEVST);
    }

    /**
     * Sets <code>value</code> as attribute value for DATE_VST using the alias name DateVst.
     * @param value value to set the DATE_VST
     */
    public void setDateVst(Timestamp value) {
        setAttributeInternal(DATEVST, value);
    }

    /**
     * Gets the attribute value for EMPNO using the alias name Empno.
     * @return the EMPNO
     */
    public String getEmpno() {
        return (String) getAttributeInternal(EMPNO);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPNO using the alias name Empno.
     * @param value value to set the EMPNO
     */
    public void setEmpno(String value) {
        setAttributeInternal(EMPNO, value);
        try {
            Key k = new Key(new Object[] { value });
            Row[] rows = getEmployeeVO1().findByKey(k, 1);
            BigDecimal empRate = (BigDecimal) rows[0].getAttribute("EmpRate");
            BigDecimal wrkHr;
            RowIterator workRows = this.getWork();
            BigDecimal sum = BigDecimal.ZERO;
            if (empRate != null) {
                while (workRows.hasNext()) {
                    Row workRow = workRows.next();
                    wrkHr = (BigDecimal) workRow.getAttribute("WrkHr");
                    sum = sum.add(wrkHr);
                    workRow.setAttribute("WrkHrRat", wrkHr.multiply(empRate));
                }
                setTtlRatedHrs(sum.multiply(empRate));
            }
            else {
                while (workRows.hasNext()) {
                    Row workRow = workRows.next();
                    wrkHr = (BigDecimal) workRow.getAttribute("WrkHr");
                    sum = sum.add(wrkHr);
                    workRow.setAttribute("WrkHrRat", null);
                }
                setTtlRatedHrs(null);
            }
            setTtlHrs(sum);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * Gets the attribute value for CLINO using the alias name Clino.
     * @return the CLINO
     */
    public String getClino() {
        if (getAttributeInternal(CLINO) != null) {
            BindingContainer bindings = BindingContext.getCurrent().getCurrentBindingsEntry();
            DCIteratorBinding parentIter = (DCIteratorBinding)bindings.get("Client1Iterator");
            Key parentKey = new Key(new Object[] { (String) getAttributeInternal(CLINO) }); 
            parentIter.setCurrentRowWithKey(parentKey.toStringFormat(true));
        }
        return (String) getAttributeInternal(CLINO); 
    }

    /**
     * Sets <code>value</code> as attribute value for CLINO using the alias name Clino.
     * @param value value to set the CLINO
     */
    public void setClino(String value) {
        setAttributeInternal(CLINO, value);
        ADFUtil.invokeEL("#{bindings.Execute.execute}");
    }


    /**
     * Gets the attribute value for TIME_FRM using the alias name TimeFrm.
     * @return the TIME_FRM
     */
    public String getTimeFrm() {
        return (String) getAttributeInternal(TIMEFRM);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_FRM using the alias name TimeFrm.
     * @param value value to set the TIME_FRM
     */
    public void setTimeFrm(String value) {
        setAttributeInternal(TIMEFRM, value);
    }

    /**
     * Gets the attribute value for TIME_TO using the alias name TimeTo.
     * @return the TIME_TO
     */
    public String getTimeTo() {
        return (String) getAttributeInternal(TIMETO);
    }

    /**
     * Sets <code>value</code> as attribute value for TIME_TO using the alias name TimeTo.
     * @param value value to set the TIME_TO
     */
    public void setTimeTo(String value) {
        setAttributeInternal(TIMETO, value);
    }

    /**
     * Gets the attribute value for CLI_RSP using the alias name CliRsp.
     * @return the CLI_RSP
     */
    public String getCliRsp() {
        return (String) getAttributeInternal(CLIRSP);
    }

    /**
     * Sets <code>value</code> as attribute value for CLI_RSP using the alias name CliRsp.
     * @param value value to set the CLI_RSP
     */
    public void setCliRsp(String value) {
        setAttributeInternal(CLIRSP, value);
    }

    /**
     * Gets the attribute value for VST_PERIOD using the alias name VstPeriod.
     * @return the VST_PERIOD
     */
    public String getVstPeriod() {
        return (String) getAttributeInternal(VSTPERIOD);
    }

    /**
     * Sets <code>value</code> as attribute value for VST_PERIOD using the alias name VstPeriod.
     * @param value value to set the VST_PERIOD
     */
    public void setVstPeriod(String value) {
        setAttributeInternal(VSTPERIOD, value);
    }

    /**
     * Gets the attribute value for EMP_RATE using the alias name EmpRate.
     * @return the EMP_RATE
     */
    public BigDecimal getEmpRate() {
        return (BigDecimal) getAttributeInternal(EMPRATE);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_RATE using the alias name EmpRate.
     * @param value value to set the EMP_RATE
     */
    public void setEmpRate(BigDecimal value) {
        setAttributeInternal(EMPRATE, value);
    }

    /**
     * Gets the attribute value for EMPNO using the alias name Empno1.
     * @return the EMPNO
     */
    public String getEmpno1() {
        return (String) getAttributeInternal(EMPNO1);
    }

    /**
     * Sets <code>value</code> as attribute value for EMPNO using the alias name Empno1.
     * @param value value to set the EMPNO
     */
    public void setEmpno1(String value) {
        setAttributeInternal(EMPNO1, value);
    }

    /**
     * Gets the attribute value for EMP_NAME using the alias name EmpName.
     * @return the EMP_NAME
     */
    public String getEmpName() {
        return (String) getAttributeInternal(EMPNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for EMP_NAME using the alias name EmpName.
     * @param value value to set the EMP_NAME
     */
    public void setEmpName(String value) {
        setAttributeInternal(EMPNAME, value);
    }

    /**
     * Gets the attribute value for CLI_NAME using the alias name CliName.
     * @return the CLI_NAME
     */
    public String getCliName() {
        return (String) getAttributeInternal(CLINAME);
    }

    /**
     * Sets <code>value</code> as attribute value for CLI_NAME using the alias name CliName.
     * @param value value to set the CLI_NAME
     */
    public void setCliName(String value) {
        setAttributeInternal(CLINAME, value);
    }

    /**
     * Gets the attribute value for CLINO using the alias name Clino1.
     * @return the CLINO
     */
    public String getClino1() {
        return (String) getAttributeInternal(CLINO1);
    }

    /**
     * Sets <code>value</code> as attribute value for CLINO using the alias name Clino1.
     * @param value value to set the CLINO
     */
    public void setClino1(String value) {
        setAttributeInternal(CLINO1, value);
    }

    /**
     * Gets the attribute value for SHEETNO using the alias name Sheetno.
     * @return the SHEETNO
     */
    public Long getSheetno() {
        return (Long) getAttributeInternal(SHEETNO);
    }

    /**
     * Sets <code>value</code> as attribute value for SHEETNO using the alias name Sheetno.
     * @param value value to set the SHEETNO
     */
    public void setSheetno(Long value) {
        setAttributeInternal(SHEETNO, value);
    }


    /**
     * Gets the attribute value for HR_FRM using the alias name HrFrm.
     * @return the HR_FRM
     */
    public String getHrFrm() {
        return (String) getAttributeInternal(HRFRM);
    }

    /**
     * Sets <code>value</code> as attribute value for HR_FRM using the alias name HrFrm.
     * @param value value to set the HR_FRM
     */
    public void setHrFrm(String value) {
        setAttributeInternal(HRFRM, value);
    }

    /**
     * Gets the attribute value for MIN_FRM using the alias name MinFrm.
     * @return the MIN_FRM
     */
    public String getMinFrm() {
        return (String) getAttributeInternal(MINFRM);
    }

    /**
     * Sets <code>value</code> as attribute value for MIN_FRM using the alias name MinFrm.
     * @param value value to set the MIN_FRM
     */
    public void setMinFrm(String value) {
        setAttributeInternal(MINFRM, value);
    }

    /**
     * Gets the attribute value for HR_TO using the alias name HrTo.
     * @return the HR_TO
     */
    public String getHrTo() {
        return (String) getAttributeInternal(HRTO);
    }

    /**
     * Sets <code>value</code> as attribute value for HR_TO using the alias name HrTo.
     * @param value value to set the HR_TO
     */
    public void setHrTo(String value) {
        setAttributeInternal(HRTO, value);
    }

    /**
     * Gets the attribute value for MIN_TO using the alias name MinTo.
     * @return the MIN_TO
     */
    public String getMinTo() {
        return (String) getAttributeInternal(MINTO);
    }

    /**
     * Sets <code>value</code> as attribute value for MIN_TO using the alias name MinTo.
     * @param value value to set the MIN_TO
     */
    public void setMinTo(String value) {
        setAttributeInternal(MINTO, value);
    }


    /**
     * Gets the attribute value for TTL_HRS using the alias name TtlHrs.
     * @return the TTL_HRS
     */
    public BigDecimal getTtlHrs() {
        return (BigDecimal) getAttributeInternal(TTLHRS);
    }

    /**
     * Sets <code>value</code> as attribute value for TTL_HRS using the alias name TtlHrs.
     * @param value value to set the TTL_HRS
     */
    public void setTtlHrs(BigDecimal value) {
        setAttributeInternal(TTLHRS, value);
    }

    /**
     * Gets the attribute value for TTL_RATED_HRS using the alias name TtlRatedHrs.
     * @return the TTL_RATED_HRS
     */
    public BigDecimal getTtlRatedHrs() {
        return (BigDecimal) getAttributeInternal(TTLRATEDHRS);
    }

    /**
     * Sets <code>value</code> as attribute value for TTL_RATED_HRS using the alias name TtlRatedHrs.
     * @param value value to set the TTL_RATED_HRS
     */
    public void setTtlRatedHrs(BigDecimal value) {
        setAttributeInternal(TTLRATEDHRS, value);
    }

    /**
     * Gets the attribute value for REMARKS using the alias name Remarks.
     * @return the REMARKS
     */
    public String getRemarks() {
        return (String) getAttributeInternal(REMARKS);
    }

    /**
     * Sets <code>value</code> as attribute value for REMARKS using the alias name Remarks.
     * @param value value to set the REMARKS
     */
    public void setRemarks(String value) {
        setAttributeInternal(REMARKS, value);
    }

    /**
     * Gets the attribute value for U_NAME using the alias name UName.
     * @return the U_NAME
     */
    public String getUName() {
        return (String) getAttributeInternal(UNAME);
    }

    /**
     * Sets <code>value</code> as attribute value for U_NAME using the alias name UName.
     * @param value value to set the U_NAME
     */
    public void setUName(String value) {
        setAttributeInternal(UNAME, value);
    }

    /**
     * Gets the associated <code>RowIterator</code> using master-detail link Work.
     */
    public RowIterator getWork() {
        return (RowIterator) getAttributeInternal(WORK);
    }

    /**
     * Gets the view accessor <code>RowSet</code> ClientVO1.
     */
    public RowSet getClientVO1() {
        return (RowSet) getAttributeInternal(CLIENTVO1);
    }


    /**
     * Gets the view accessor <code>RowSet</code> EmployeeVO1.
     */
    public RowSet getEmployeeVO1() {
        return (RowSet) getAttributeInternal(EMPLOYEEVO1);
    }


}

