package com.computec.sitevisit.model.uiview;

import com.computec.sitevisit.model.common.ADFUtil;

import java.math.BigDecimal;
import oracle.jbo.RowSet;
import oracle.jbo.domain.DBSequence;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 06 10:33:50 EEST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class WorkVORowImpl extends ViewRowImpl {


    public static final int ENTITY_WORKEO = 0;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    protected enum AttributesEnum {
        WrkId,
        WrkChrgTyp,
        WrkDesc,
        WrkHr,
        WrkHrRat,
        CliPrj,
        SitevstId,
        Sitevst,
        VisitReport;
        private static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        protected int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        protected static final int firstIndex() {
            return firstIndex;
        }

        protected static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        protected static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int WRKID = AttributesEnum.WrkId.index();
    public static final int WRKCHRGTYP = AttributesEnum.WrkChrgTyp.index();
    public static final int WRKDESC = AttributesEnum.WrkDesc.index();
    public static final int WRKHR = AttributesEnum.WrkHr.index();
    public static final int WRKHRRAT = AttributesEnum.WrkHrRat.index();
    public static final int CLIPRJ = AttributesEnum.CliPrj.index();
    public static final int SITEVSTID = AttributesEnum.SitevstId.index();
    public static final int SITEVST = AttributesEnum.Sitevst.index();
    public static final int VISITREPORT = AttributesEnum.VisitReport.index();

    /**
     * This is the default constructor (do not remove).
     */
    public WorkVORowImpl() {
    }

    /**
     * Gets WorkEO entity object.
     * @return the WorkEO
     */
    public EntityImpl getWorkEO() {
        return (EntityImpl) getEntity(ENTITY_WORKEO);
    }


    /**
     * Gets the attribute value for WRK_ID using the alias name WrkId.
     * @return the WRK_ID
     */
    public DBSequence getWrkId() {
        return (DBSequence) getAttributeInternal(WRKID);
    }

    /**
     * Sets <code>value</code> as attribute value for WRK_ID using the alias name WrkId.
     * @param value value to set the WRK_ID
     */
    public void setWrkId(DBSequence value) {
        setAttributeInternal(WRKID, value);
    }

    /**
     * Gets the attribute value for WRK_CHRG_TYP using the alias name WrkChrgTyp.
     * @return the WRK_CHRG_TYP
     */
    public String getWrkChrgTyp() {
        return (String) getAttributeInternal(WRKCHRGTYP);
    }

    /**
     * Sets <code>value</code> as attribute value for WRK_CHRG_TYP using the alias name WrkChrgTyp.
     * @param value value to set the WRK_CHRG_TYP
     */
    public void setWrkChrgTyp(String value) {
        setAttributeInternal(WRKCHRGTYP, value);
    }

    /**
     * Gets the attribute value for WRK_DESC using the alias name WrkDesc.
     * @return the WRK_DESC
     */
    public String getWrkDesc() {
        return (String) getAttributeInternal(WRKDESC);
    }

    /**
     * Sets <code>value</code> as attribute value for WRK_DESC using the alias name WrkDesc.
     * @param value value to set the WRK_DESC
     */
    public void setWrkDesc(String value) {
        setAttributeInternal(WRKDESC, value);
    }

    /**
     * Gets the attribute value for WRK_HR using the alias name WrkHr.
     * @return the WRK_HR
     */
    public BigDecimal getWrkHr() {
        return (BigDecimal) getAttributeInternal(WRKHR);
    }

    /**
     * Sets <code>value</code> as attribute value for WRK_HR using the alias name WrkHr.
     * @param value value to set the WRK_HR
     */
    public void setWrkHr(BigDecimal value) {
        setAttributeInternal(WRKHR, value);
        BigDecimal calHr =
            (BigDecimal) ADFUtil.evaluateEL("#{row.bindings.WrkHr.inputValue * bindings.EmpRate.inputValue}");
        setWrkHrRat(calHr);
        String empno = (String) getSitevst().getAttribute("Empno");
        getSitevst().setAttribute("Empno", empno);
    }

    /**
     * Gets the attribute value for WRK_HR_RAT using the alias name WrkHrRat.
     * @return the WRK_HR_RAT
     */
    public BigDecimal getWrkHrRat() {
        return (BigDecimal) getAttributeInternal(WRKHRRAT);
    }

    /**
     * Sets <code>value</code> as attribute value for WRK_HR_RAT using the alias name WrkHrRat.
     * @param value value to set the WRK_HR_RAT
     */
    public void setWrkHrRat(BigDecimal value) {
        setAttributeInternal(WRKHRRAT, value);
    }


    /**
     * Gets the attribute value for CLI_PRJ using the alias name CliPrj.
     * @return the CLI_PRJ
     */
    public String getCliPrj() {
        return (String) getAttributeInternal(CLIPRJ);
    }

    /**
     * Sets <code>value</code> as attribute value for CLI_PRJ using the alias name CliPrj.
     * @param value value to set the CLI_PRJ
     */
    public void setCliPrj(String value) {
        setAttributeInternal(CLIPRJ, value);
    }

    /**
     * Gets the attribute value for SITEVST_ID using the alias name SitevstId.
     * @return the SITEVST_ID
     */
    public BigDecimal getSitevstId() {
        return (BigDecimal) getAttributeInternal(SITEVSTID);
    }

    /**
     * Sets <code>value</code> as attribute value for SITEVST_ID using the alias name SitevstId.
     * @param value value to set the SITEVST_ID
     */
    public void setSitevstId(BigDecimal value) {
        setAttributeInternal(SITEVSTID, value);
    }


    /**
     * Gets the associated <code>SitevstVORowImpl</code> using master-detail link Sitevst.
     */
    public SitevstVORowImpl getSitevst() {
        return (SitevstVORowImpl) getAttributeInternal(SITEVST);
    }

    /**
     * Sets the master-detail link Sitevst between this object and <code>value</code>.
     */
    public void setSitevst(SitevstVORowImpl value) {
        setAttributeInternal(SITEVST, value);
    }

    /**
     * Gets the associated <code>ViewRowImpl</code> using master-detail link VisitReport.
     */
    public ViewRowImpl getVisitReport() {
        return (ViewRowImpl) getAttributeInternal(VISITREPORT);
    }

    /**
     * Sets the master-detail link VisitReport between this object and <code>value</code>.
     */
    public void setVisitReport(ViewRowImpl value) {
        setAttributeInternal(VISITREPORT, value);
    }


}

